### ISSUE TITLE
дом

### ISSUE THREAD

**Issue by a4men22** [microsoft/vscode-loc#1489]
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode-loc/issues/1038
- [ ] https://github.com/microsoft/vscode-loc/issues/1199
- [ ] https://github.com/microsoft/vscode-loc/issues/1029
```

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 912456).

**Comment by a4men22** [comment]
![b4d4859a11c87019f5cfe2390cfe3c9e](https://github.com/microsoft/vscode-loc/assets/35773576/89bb3c24-49cf-40c2-adf1-8dd62a525239)
